#!/usr/bin/env ruby

# PROVIDE: netif
# REQUIRE: atm1 cleanvar ipfilter FILESYSTEMS serial sppp sysctl
# KEYWORD: nojail

require 'rubygems'
require 'lacuna-core/script'

start do |*devices|
  log "Starting interfaces" do
    interfaces = Lacuna.network.interfaces
    interfaces.select! {|d| devices.any?{|d2| d.device == d2 || d.id == d2 } } if devices.size > 0
    interfaces.each {|i| i.start}
  end
end

stop do |*devices|
  log "Stopping interfaces" do
    interfaces = Lacuna.network.interfaces
    interfaces.select! {|d| devices.any?{|d2| d.device == d2 || d.id == d2 } } if devices.size > 0
    interfaces.each {|i| i.stop}
  end
end
