source "http://rubygems.org"

gem 'thin'
gem 'i18n'
gem 'sinatra', :require=>'sinatra/base'
#gem 'haml'
gem 'json'
gem 'rest-client', :require=>'restclient'
group :development do
  gem "sinatra-reloader"
  gem 'rake'
  gem 'rspec'
end