#!/usr/bin/env ruby

# PROVIDE: netif
# REQUIRE: atm1 cleanvar ipfilter FILESYSTEMS serial sppp sysctl
# KEYWORD: nojail

def start(*devices)
  if devices.size == 0
    BSD::Network.vlans
  end
  interfaces = BSD::Network.configured_interfaces
  interfaces.select! {|d| devices.any?{|d2| d.device==d2 } } if devices.size > 0
  interfaces.each {|i| i.start}
end

def stop(*devices)
  puts "Stopping interfaces..."
#  interfaces = BSD::Network.configured_interfaces
#  interfaces.select! {|d| devices.any?{|d2| d.device==d2 } } if devices.size > 0
#  interfaces.each {|i| i.stop}
end

cmd = ARGV.shift || 'start'
puts respond_to?(:start)

send(cmd, *ARGV) if respond_to?(cmd.to_sym)